# Generated by Django 4.0.2 on 2022-02-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samochody', '0002_samochody_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samochody',
            name='model',
        ),
        migrations.AddField(
            model_name='samochody',
            name='rozmiar',
            field=models.CharField(choices=[('L', 'duża'), ('M', 'średnia'), ('S', 'mała')], default='L', max_length=1),
        ),
    ]
