# Generated by Django 4.0.2 on 2022-02-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samochody', '0003_remove_samochody_model_samochody_rozmiar'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochody',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='zdjecia'),
        ),
    ]
