# Generated by Django 4.0.2 on 2022-02-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samochody', '0004_samochody_zdjecie'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochody',
            name='opis',
            field=models.TextField(default=''),
        ),
    ]
