# Generated by Django 4.0.2 on 2022-02-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samochody', '0005_samochody_opis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samochody',
            name='rozmiar',
        ),
    ]
