# Generated by Django 4.0.2 on 2022-02-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samochody', '0006_remove_samochody_rozmiar'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochody',
            name='salon',
            field=models.ImageField(blank=True, null=True, upload_to='zdjecia'),
        ),
    ]
